name: simple_vcf
description: A simple way of handeling simple_vcf files.
version: 1.0.0
repository: https://github.com/SirToby-Gore/dart-simple_vcf

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
